spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/SimuladorTipoInvestimento
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddlAuto: update
        showSql: true
    main:
        allow-circular-references: true
server:
    port: 3333
